# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: y1m7x's Blog
subtitle: 一个前端菜鸟的成长笔记
description: 人总需要点什么来坚持下去。或是希望，或是信仰。我和这个世界不熟，但我怀有期待。
author: y1m7x
language: zh-CN
timezone:
avatar: http://7xp8kh.com1.z0.glb.clouddn.com/touxiang14257483.jpg

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://igeek.wang
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: indigo

# Social links
social:
  github: https://github.com/yangmaoxin
  weibo: http://weibo.com/349873
  # douban: http://douban.com/people/your-user-name
  # zhihu: http://www.zhihu.com/people/iymx


disqus_shortname: iymx

# hexo sitemap网站地图
# sitemap:
# path: sitemap.xml
# baidusitemap:
# path: baidusitemap.xml


# Deployment
## Docs: http://hexo.io/docs/deployment.html
#deploy:
#  type: git
#  repository: git@github.com:yangmaoxin/yangmaoxin.github.io.git
#  branch: master

deploy:
  type: git
  message: ""
  repo: 
    github: git@github.com:yangmaoxin/yangmaoxin.github.io.git,master
#  coding: git@git.coding.net:iymx/iymx.git,master
