author: moxinn # 作者
description: Moxinn's blog
keyword: hexo-theme, vuejs
favicon: 

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment or uyan or valine

comment: valine


# 文章页留言内容，hexo中所有变量及辅助函数等均可调用，具体请查阅 hexo.io
postMessage: 转发请注明出处：<a href="<%- url_for(page.path).replace(/index\.html$/, '') %>" target="_blank" rel="external"><%- url.replace(/index\.html$/, '') %></a>

# 站长统计，如要开启，输入CNZZ站点id，如 cnzz: 1255152447
cnzz_analytics: 1262387845

# “不蒜子”访问量统计，详见 http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  site_uv: 站点总访客数：
  site_pv: 站点总访问量：


# icp备案号  ICP_license: 京ICP备1234556号-1
ICP_license: false


# gitment config
gitment_owner: moxinn
gitment_repo: yangmaoxin.github.io
gitment_oauth_id: 0f87e490e00ee3fd87ef
gitment_oauth_secret: 4a9d2b148e7971c2201ad12131ce8bf8159ccd2e

# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id: 

## Valine评论
valine:
   enable: true
   appId: gG40u256e5d4nmqKAwbjlz9S-gzGzoHsz
   appKey: kQr7vEhzEzVFakiH2IkpTIzx
   placeholder: 说点什么吧
   notify: false
   verify: false
   avatar: mm
   meta: nick,mail
   pageSize: 10

about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: https://avatars1.githubusercontent.com/u/13795227?s=400
  description: "人总需要点什么来坚持下去。或是希望，或是信仰。我和这个世界不熟，但我怀有期待。"
  weibo_username: maoxin
  twitter_username: y1m7x
  github_username: yangmaoxin
  zhihu_username: moxinn
  douban_username: y

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
